{"historyId": "5c15b4ce61d90abfc0475b4bbe4acfa0", "status": "broken", "stop": 1604965712436, "statusDetails": {"trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\npy_practice\\py_allure_p.py:17: Exception", "message": "Exception: oops"}, "testCaseId": "f513e7adbd1ed2f467aa8c9614cdde78", "name": "test_broken", "labels": [{"name": "parentSuite", "value": "py_practice"}, {"name": "suite", "value": "py_allure_p"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "20684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_practice.py_allure_p"}], "fullName": "py_practice.py_allure_p#test_broken", "start": 1604965712436, "uuid": "40215588-e45c-45a2-8f3d-921da0df425d"}