{"name": "test_div2[5-2-None]", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'Exception'>", "trace": "self = <test_pytest.tests.test_calc.TestCalc object at 0x00000263C03E7670>, i = 5, j = 2, k = None\n\n    @pytest.mark.parametrize('i,j,k', [\n        [2, 'q',10],\n        [5, 2,None]\n    ])\n    def test_div2(self, i, j, k):\n        # 括号中为抛出的异常，如果不知道具体的异常就直接使用Exception\n        with pytest.raises(Exception):\n>           assert self.calc.div(i, j)\nE           Failed: DID NOT RAISE <class 'Exception'>\n\ntest_pytest\\tests\\test_calc.py:111: Failed"}, "parameters": [{"name": "i", "value": "5"}, {"name": "j", "value": "2"}, {"name": "k", "value": "None"}], "start": 1605403013692, "stop": 1605403013692, "uuid": "487062fc-5c74-4859-b53e-dbc68c6ee78c", "historyId": "8cac577defe6738e3c0d0be5af0b553c", "testCaseId": "a13da675cde8e2fc5c56d4477e8afafa", "fullName": "test_pytest.tests.test_calc.TestCalc#test_div2", "labels": [{"name": "parentSuite", "value": "test_pytest.tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "16464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.tests.test_calc"}]}