{"fullName": "py_practice.test_alluremode#test_broken", "name": "test_broken", "historyId": "7b69f26bddf363982f842cc3ad7d85f8", "stop": 1605049796038, "testCaseId": "df9add288873f3b6bce5d13274225680", "statusDetails": {"trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\npy_practice\\test_alluremode.py:17: Exception", "message": "Exception: oops"}, "uuid": "43007292-7a01-4380-8f17-d254575cecfa", "start": 1605049796037, "labels": [{"name": "parentSuite", "value": "py_practice"}, {"name": "suite", "value": "test_alluremode"}, {"name": "host", "value": "LAPTOP-6QKFPKJ6"}, {"name": "thread", "value": "18172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_practice.test_alluremode"}], "status": "broken"}