{"statusDetails": {"trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\npy_practice\\py_allure_p.py:17: Exception", "message": "Exception: oops"}, "start": 1605011566975, "uuid": "849eecc1-15f8-4d58-8860-7b7f0cf66947", "fullName": "py_practice.py_allure_p#test_broken", "historyId": "5c15b4ce61d90abfc0475b4bbe4acfa0", "labels": [{"value": "py_practice", "name": "parentSuite"}, {"value": "py_allure_p", "name": "suite"}, {"value": "LAPTOP-6QKFPKJ6", "name": "host"}, {"value": "17056-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "py_practice.py_allure_p", "name": "package"}], "status": "broken", "stop": 1605011566975, "testCaseId": "f513e7adbd1ed2f467aa8c9614cdde78", "name": "test_broken"}